{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4ce4f347-a90b-48f0-bc30-15c220199745",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading Game...\n",
      "Loaded!\n",
      "Starting Match...\n",
      "\n",
      "Standard Backgammon Games are often played to 3, 5, 7, 9, 11, or 15 points.\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "What score would you like to play to? 3\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Player 1 rolled a 3, Player 2 rolled a 6\n",
      "6 is higher than 3 so Player 2 goes first!\n",
      "Starting die are 3 and 6\n",
      "0\n",
      "\n",
      "\n",
      "\u001b[1mPlayer 2 Home\u001b[0m\n",
      "\n",
      "Pieces Born Off: 0\n",
      "------------------------------\n",
      "\n",
      "23    -    2\n",
      "22    -    0\n",
      "21    -    0\n",
      "20    -    0\n",
      "19    -    0\n",
      "18    -    -5\n",
      "\n",
      "Player 1 Pieces on Bar: 0\n",
      "\n",
      "17    -    0\n",
      "16    -    -3\n",
      "15    -    0\n",
      "14    -    0\n",
      "13    -    0\n",
      "12    -    5\n",
      "11    -    -5\n",
      "10    -    0\n",
      "9    -    0\n",
      "8    -    0\n",
      "7    -    3\n",
      "6    -    0\n",
      "\n",
      "Player 2 Pieces on Bar: 0\n",
      "\n",
      "5    -    5\n",
      "4    -    0\n",
      "3    -    0\n",
      "2    -    0\n",
      "1    -    0\n",
      "0    -    -2\n",
      "\n",
      "------------------------------\n",
      "Pieces Born Off: 0\n",
      "\n",
      "\u001b[1mPlayer 1 Home\u001b[0m\n",
      "\n",
      "\n",
      "Move Number     Starting Position    End Position    Die Used  \n",
      "------------------------------------------------------------\n",
      "0               16                   19              3         \n",
      "1               0                    3               3         \n",
      "2               16                   22              6         \n",
      "3               11                   14              3         \n",
      "4               0                    6               6         \n",
      "5               11                   17              6         \n",
      "6               18                   21              3         \n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Choose an eligible move:  0\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\u001b[1mPlayer 2 Home\u001b[0m\n",
      "\n",
      "Pieces Born Off: 0\n",
      "------------------------------\n",
      "\n",
      "23    -    2\n",
      "22    -    0\n",
      "21    -    0\n",
      "20    -    0\n",
      "19    -    -1\n",
      "18    -    -5\n",
      "\n",
      "Player 1 Pieces on Bar: 0\n",
      "\n",
      "17    -    0\n",
      "16    -    -2\n",
      "15    -    0\n",
      "14    -    0\n",
      "13    -    0\n",
      "12    -    5\n",
      "11    -    -5\n",
      "10    -    0\n",
      "9    -    0\n",
      "8    -    0\n",
      "7    -    3\n",
      "6    -    0\n",
      "\n",
      "Player 2 Pieces on Bar: 0\n",
      "\n",
      "5    -    5\n",
      "4    -    0\n",
      "3    -    0\n",
      "2    -    0\n",
      "1    -    0\n",
      "0    -    -2\n",
      "\n",
      "------------------------------\n",
      "Pieces Born Off: 0\n",
      "\n",
      "\u001b[1mPlayer 1 Home\u001b[0m\n",
      "\n",
      "\n",
      "Move Number     Starting Position    End Position    Die Used  \n",
      "------------------------------------------------------------\n",
      "0               16                   22              6         \n",
      "1               0                    6               6         \n",
      "2               11                   17              6         \n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Choose an eligible move:  0\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\u001b[1mPlayer 2 Home\u001b[0m\n",
      "\n",
      "Pieces Born Off: 0\n",
      "------------------------------\n",
      "\n",
      "23    -    2\n",
      "22    -    -1\n",
      "21    -    0\n",
      "20    -    0\n",
      "19    -    -1\n",
      "18    -    -5\n",
      "\n",
      "Player 1 Pieces on Bar: 0\n",
      "\n",
      "17    -    0\n",
      "16    -    -1\n",
      "15    -    0\n",
      "14    -    0\n",
      "13    -    0\n",
      "12    -    5\n",
      "11    -    -5\n",
      "10    -    0\n",
      "9    -    0\n",
      "8    -    0\n",
      "7    -    3\n",
      "6    -    0\n",
      "\n",
      "Player 2 Pieces on Bar: 0\n",
      "\n",
      "5    -    5\n",
      "4    -    0\n",
      "3    -    0\n",
      "2    -    0\n",
      "1    -    0\n",
      "0    -    -2\n",
      "\n",
      "------------------------------\n",
      "Pieces Born Off: 0\n",
      "\n",
      "\u001b[1mPlayer 1 Home\u001b[0m\n",
      "\n",
      "\n",
      "Switching Turns...\n",
      "Player 1's Turn\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Press enter to roll die \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "You rolled [2, 2, 2, 2]\n",
      "1\n",
      "\n",
      "\n",
      "\u001b[1mPlayer 2 Home\u001b[0m\n",
      "\n",
      "Pieces Born Off: 0\n",
      "------------------------------\n",
      "\n",
      "23    -    2\n",
      "22    -    -1\n",
      "21    -    0\n",
      "20    -    0\n",
      "19    -    -1\n",
      "18    -    -5\n",
      "\n",
      "Player 1 Pieces on Bar: 0\n",
      "\n",
      "17    -    0\n",
      "16    -    -1\n",
      "15    -    0\n",
      "14    -    0\n",
      "13    -    0\n",
      "12    -    5\n",
      "11    -    -5\n",
      "10    -    0\n",
      "9    -    0\n",
      "8    -    0\n",
      "7    -    3\n",
      "6    -    0\n",
      "\n",
      "Player 2 Pieces on Bar: 0\n",
      "\n",
      "5    -    5\n",
      "4    -    0\n",
      "3    -    0\n",
      "2    -    0\n",
      "1    -    0\n",
      "0    -    -2\n",
      "\n",
      "------------------------------\n",
      "Pieces Born Off: 0\n",
      "\n",
      "\u001b[1mPlayer 1 Home\u001b[0m\n",
      "\n",
      "\n",
      "Move Number     Starting Position    End Position    Die Used  \n",
      "------------------------------------------------------------\n",
      "0               5                    3               2         \n",
      "1               23                   21              2         \n",
      "2               12                   10              2         \n",
      "3               7                    5               2         \n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Choose an eligible move:  0\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\u001b[1mPlayer 2 Home\u001b[0m\n",
      "\n",
      "Pieces Born Off: 0\n",
      "------------------------------\n",
      "\n",
      "23    -    2\n",
      "22    -    -1\n",
      "21    -    0\n",
      "20    -    0\n",
      "19    -    -1\n",
      "18    -    -5\n",
      "\n",
      "Player 1 Pieces on Bar: 0\n",
      "\n",
      "17    -    0\n",
      "16    -    -1\n",
      "15    -    0\n",
      "14    -    0\n",
      "13    -    0\n",
      "12    -    5\n",
      "11    -    -5\n",
      "10    -    0\n",
      "9    -    0\n",
      "8    -    0\n",
      "7    -    3\n",
      "6    -    0\n",
      "\n",
      "Player 2 Pieces on Bar: 0\n",
      "\n",
      "5    -    4\n",
      "4    -    0\n",
      "3    -    1\n",
      "2    -    0\n",
      "1    -    0\n",
      "0    -    -2\n",
      "\n",
      "------------------------------\n",
      "Pieces Born Off: 0\n",
      "\n",
      "\u001b[1mPlayer 1 Home\u001b[0m\n",
      "\n",
      "\n",
      "Move Number     Starting Position    End Position    Die Used  \n",
      "------------------------------------------------------------\n",
      "0               23                   21              2         \n",
      "1               5                    3               2         \n",
      "2               12                   10              2         \n",
      "3               3                    1               2         \n",
      "4               7                    5               2         \n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Choose an eligible move:  1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\u001b[1mPlayer 2 Home\u001b[0m\n",
      "\n",
      "Pieces Born Off: 0\n",
      "------------------------------\n",
      "\n",
      "23    -    2\n",
      "22    -    -1\n",
      "21    -    0\n",
      "20    -    0\n",
      "19    -    -1\n",
      "18    -    -5\n",
      "\n",
      "Player 1 Pieces on Bar: 0\n",
      "\n",
      "17    -    0\n",
      "16    -    -1\n",
      "15    -    0\n",
      "14    -    0\n",
      "13    -    0\n",
      "12    -    5\n",
      "11    -    -5\n",
      "10    -    0\n",
      "9    -    0\n",
      "8    -    0\n",
      "7    -    3\n",
      "6    -    0\n",
      "\n",
      "Player 2 Pieces on Bar: 0\n",
      "\n",
      "5    -    3\n",
      "4    -    0\n",
      "3    -    2\n",
      "2    -    0\n",
      "1    -    0\n",
      "0    -    -2\n",
      "\n",
      "------------------------------\n",
      "Pieces Born Off: 0\n",
      "\n",
      "\u001b[1mPlayer 1 Home\u001b[0m\n",
      "\n",
      "\n",
      "Move Number     Starting Position    End Position    Die Used  \n",
      "------------------------------------------------------------\n",
      "0               23                   21              2         \n",
      "1               5                    3               2         \n",
      "2               12                   10              2         \n",
      "3               3                    1               2         \n",
      "4               7                    5               2         \n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Choose an eligible move:  1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\u001b[1mPlayer 2 Home\u001b[0m\n",
      "\n",
      "Pieces Born Off: 0\n",
      "------------------------------\n",
      "\n",
      "23    -    2\n",
      "22    -    -1\n",
      "21    -    0\n",
      "20    -    0\n",
      "19    -    -1\n",
      "18    -    -5\n",
      "\n",
      "Player 1 Pieces on Bar: 0\n",
      "\n",
      "17    -    0\n",
      "16    -    -1\n",
      "15    -    0\n",
      "14    -    0\n",
      "13    -    0\n",
      "12    -    5\n",
      "11    -    -5\n",
      "10    -    0\n",
      "9    -    0\n",
      "8    -    0\n",
      "7    -    3\n",
      "6    -    0\n",
      "\n",
      "Player 2 Pieces on Bar: 0\n",
      "\n",
      "5    -    2\n",
      "4    -    0\n",
      "3    -    3\n",
      "2    -    0\n",
      "1    -    0\n",
      "0    -    -2\n",
      "\n",
      "------------------------------\n",
      "Pieces Born Off: 0\n",
      "\n",
      "\u001b[1mPlayer 1 Home\u001b[0m\n",
      "\n",
      "\n",
      "Move Number     Starting Position    End Position    Die Used  \n",
      "------------------------------------------------------------\n",
      "0               23                   21              2         \n",
      "1               5                    3               2         \n",
      "2               12                   10              2         \n",
      "3               3                    1               2         \n",
      "4               7                    5               2         \n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Choose an eligible move:  1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\u001b[1mPlayer 2 Home\u001b[0m\n",
      "\n",
      "Pieces Born Off: 0\n",
      "------------------------------\n",
      "\n",
      "23    -    2\n",
      "22    -    -1\n",
      "21    -    0\n",
      "20    -    0\n",
      "19    -    -1\n",
      "18    -    -5\n",
      "\n",
      "Player 1 Pieces on Bar: 0\n",
      "\n",
      "17    -    0\n",
      "16    -    -1\n",
      "15    -    0\n",
      "14    -    0\n",
      "13    -    0\n",
      "12    -    5\n",
      "11    -    -5\n",
      "10    -    0\n",
      "9    -    0\n",
      "8    -    0\n",
      "7    -    3\n",
      "6    -    0\n",
      "\n",
      "Player 2 Pieces on Bar: 0\n",
      "\n",
      "5    -    1\n",
      "4    -    0\n",
      "3    -    4\n",
      "2    -    0\n",
      "1    -    0\n",
      "0    -    -2\n",
      "\n",
      "------------------------------\n",
      "Pieces Born Off: 0\n",
      "\n",
      "\u001b[1mPlayer 1 Home\u001b[0m\n",
      "\n",
      "\n",
      "Switching Turns...\n",
      "Player 2's Turn\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Press enter to roll die \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "You rolled [5, 5, 5, 5]\n",
      "2\n",
      "\n",
      "\n",
      "\u001b[1mPlayer 2 Home\u001b[0m\n",
      "\n",
      "Pieces Born Off: 0\n",
      "------------------------------\n",
      "\n",
      "23    -    2\n",
      "22    -    -1\n",
      "21    -    0\n",
      "20    -    0\n",
      "19    -    -1\n",
      "18    -    -5\n",
      "\n",
      "Player 1 Pieces on Bar: 0\n",
      "\n",
      "17    -    0\n",
      "16    -    -1\n",
      "15    -    0\n",
      "14    -    0\n",
      "13    -    0\n",
      "12    -    5\n",
      "11    -    -5\n",
      "10    -    0\n",
      "9    -    0\n",
      "8    -    0\n",
      "7    -    3\n",
      "6    -    0\n",
      "\n",
      "Player 2 Pieces on Bar: 0\n",
      "\n",
      "5    -    1\n",
      "4    -    0\n",
      "3    -    4\n",
      "2    -    0\n",
      "1    -    0\n",
      "0    -    -2\n",
      "\n",
      "------------------------------\n",
      "Pieces Born Off: 0\n",
      "\n",
      "\u001b[1mPlayer 1 Home\u001b[0m\n",
      "\n",
      "\n",
      "Move Number     Starting Position    End Position    Die Used  \n",
      "------------------------------------------------------------\n",
      "0               0                    5               5         \n",
      "1               16                   21              5         \n",
      "2               11                   16              5         \n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Choose an eligible move:  0\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\u001b[1mPlayer 2 Home\u001b[0m\n",
      "\n",
      "Pieces Born Off: 0\n",
      "------------------------------\n",
      "\n",
      "23    -    2\n",
      "22    -    -1\n",
      "21    -    0\n",
      "20    -    0\n",
      "19    -    -1\n",
      "18    -    -5\n",
      "\n",
      "Player 1 Pieces on Bar: 1\n",
      "\n",
      "17    -    0\n",
      "16    -    -1\n",
      "15    -    0\n",
      "14    -    0\n",
      "13    -    0\n",
      "12    -    5\n",
      "11    -    -5\n",
      "10    -    0\n",
      "9    -    0\n",
      "8    -    0\n",
      "7    -    3\n",
      "6    -    0\n",
      "\n",
      "Player 2 Pieces on Bar: 0\n",
      "\n",
      "5    -    -1\n",
      "4    -    0\n",
      "3    -    4\n",
      "2    -    0\n",
      "1    -    0\n",
      "0    -    -1\n",
      "\n",
      "------------------------------\n",
      "Pieces Born Off: 0\n",
      "\n",
      "\u001b[1mPlayer 1 Home\u001b[0m\n",
      "\n",
      "\n",
      "Move Number     Starting Position    End Position    Die Used  \n",
      "------------------------------------------------------------\n",
      "0               0                    5               5         \n",
      "1               5                    10              5         \n",
      "2               16                   21              5         \n",
      "3               11                   16              5         \n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Choose an eligible move:  0\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\u001b[1mPlayer 2 Home\u001b[0m\n",
      "\n",
      "Pieces Born Off: 0\n",
      "------------------------------\n",
      "\n",
      "23    -    2\n",
      "22    -    -1\n",
      "21    -    0\n",
      "20    -    0\n",
      "19    -    -1\n",
      "18    -    -5\n",
      "\n",
      "Player 1 Pieces on Bar: 1\n",
      "\n",
      "17    -    0\n",
      "16    -    -1\n",
      "15    -    0\n",
      "14    -    0\n",
      "13    -    0\n",
      "12    -    5\n",
      "11    -    -5\n",
      "10    -    0\n",
      "9    -    0\n",
      "8    -    0\n",
      "7    -    3\n",
      "6    -    0\n",
      "\n",
      "Player 2 Pieces on Bar: 0\n",
      "\n",
      "5    -    -2\n",
      "4    -    0\n",
      "3    -    4\n",
      "2    -    0\n",
      "1    -    0\n",
      "0    -    0\n",
      "\n",
      "------------------------------\n",
      "Pieces Born Off: 0\n",
      "\n",
      "\u001b[1mPlayer 1 Home\u001b[0m\n",
      "\n",
      "\n",
      "Move Number     Starting Position    End Position    Die Used  \n",
      "------------------------------------------------------------\n",
      "0               5                    10              5         \n",
      "1               16                   21              5         \n",
      "2               11                   16              5         \n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Choose an eligible move:  0\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\u001b[1mPlayer 2 Home\u001b[0m\n",
      "\n",
      "Pieces Born Off: 0\n",
      "------------------------------\n",
      "\n",
      "23    -    2\n",
      "22    -    -1\n",
      "21    -    0\n",
      "20    -    0\n",
      "19    -    -1\n",
      "18    -    -5\n",
      "\n",
      "Player 1 Pieces on Bar: 1\n",
      "\n",
      "17    -    0\n",
      "16    -    -1\n",
      "15    -    0\n",
      "14    -    0\n",
      "13    -    0\n",
      "12    -    5\n",
      "11    -    -5\n",
      "10    -    -1\n",
      "9    -    0\n",
      "8    -    0\n",
      "7    -    3\n",
      "6    -    0\n",
      "\n",
      "Player 2 Pieces on Bar: 0\n",
      "\n",
      "5    -    -1\n",
      "4    -    0\n",
      "3    -    4\n",
      "2    -    0\n",
      "1    -    0\n",
      "0    -    0\n",
      "\n",
      "------------------------------\n",
      "Pieces Born Off: 0\n",
      "\n",
      "\u001b[1mPlayer 1 Home\u001b[0m\n",
      "\n",
      "\n",
      "Move Number     Starting Position    End Position    Die Used  \n",
      "------------------------------------------------------------\n",
      "0               16                   21              5         \n",
      "1               5                    10              5         \n",
      "2               11                   16              5         \n",
      "3               10                   15              5         \n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Choose an eligible move:  0\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\u001b[1mPlayer 2 Home\u001b[0m\n",
      "\n",
      "Pieces Born Off: 0\n",
      "------------------------------\n",
      "\n",
      "23    -    2\n",
      "22    -    -1\n",
      "21    -    -1\n",
      "20    -    0\n",
      "19    -    -1\n",
      "18    -    -5\n",
      "\n",
      "Player 1 Pieces on Bar: 1\n",
      "\n",
      "17    -    0\n",
      "16    -    0\n",
      "15    -    0\n",
      "14    -    0\n",
      "13    -    0\n",
      "12    -    5\n",
      "11    -    -5\n",
      "10    -    -1\n",
      "9    -    0\n",
      "8    -    0\n",
      "7    -    3\n",
      "6    -    0\n",
      "\n",
      "Player 2 Pieces on Bar: 0\n",
      "\n",
      "5    -    -1\n",
      "4    -    0\n",
      "3    -    4\n",
      "2    -    0\n",
      "1    -    0\n",
      "0    -    0\n",
      "\n",
      "------------------------------\n",
      "Pieces Born Off: 0\n",
      "\n",
      "\u001b[1mPlayer 1 Home\u001b[0m\n",
      "\n",
      "\n",
      "Switching Turns...\n",
      "Player 1's Turn\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Press enter to roll die \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "You rolled [5, 6]\n",
      "3\n",
      "\n",
      "\n",
      "\u001b[1mPlayer 2 Home\u001b[0m\n",
      "\n",
      "Pieces Born Off: 0\n",
      "------------------------------\n",
      "\n",
      "23    -    2\n",
      "22    -    -1\n",
      "21    -    -1\n",
      "20    -    0\n",
      "19    -    -1\n",
      "18    -    -5\n",
      "\n",
      "Player 1 Pieces on Bar: 1\n",
      "\n",
      "17    -    0\n",
      "16    -    0\n",
      "15    -    0\n",
      "14    -    0\n",
      "13    -    0\n",
      "12    -    5\n",
      "11    -    -5\n",
      "10    -    -1\n",
      "9    -    0\n",
      "8    -    0\n",
      "7    -    3\n",
      "6    -    0\n",
      "\n",
      "Player 2 Pieces on Bar: 0\n",
      "\n",
      "5    -    -1\n",
      "4    -    0\n",
      "3    -    4\n",
      "2    -    0\n",
      "1    -    0\n",
      "0    -    0\n",
      "\n",
      "------------------------------\n",
      "Pieces Born Off: 0\n",
      "\n",
      "\u001b[1mPlayer 1 Home\u001b[0m\n",
      "\n",
      "\n",
      "Must remove pieces from bar first!\n",
      "Move Number     Starting Position    End Position    Die Used  \n",
      "------------------------------------------------------------\n",
      "0               Bar                  19              5         \n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Choose an eligible move:  0\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\u001b[1mPlayer 2 Home\u001b[0m\n",
      "\n",
      "Pieces Born Off: 0\n",
      "------------------------------\n",
      "\n",
      "23    -    2\n",
      "22    -    -1\n",
      "21    -    -1\n",
      "20    -    0\n",
      "19    -    1\n",
      "18    -    -5\n",
      "\n",
      "Player 1 Pieces on Bar: 0\n",
      "\n",
      "17    -    0\n",
      "16    -    0\n",
      "15    -    0\n",
      "14    -    0\n",
      "13    -    0\n",
      "12    -    5\n",
      "11    -    -5\n",
      "10    -    -1\n",
      "9    -    0\n",
      "8    -    0\n",
      "7    -    3\n",
      "6    -    0\n",
      "\n",
      "Player 2 Pieces on Bar: -1\n",
      "\n",
      "5    -    -1\n",
      "4    -    0\n",
      "3    -    4\n",
      "2    -    0\n",
      "1    -    0\n",
      "0    -    0\n",
      "\n",
      "------------------------------\n",
      "Pieces Born Off: 0\n",
      "\n",
      "\u001b[1mPlayer 1 Home\u001b[0m\n",
      "\n",
      "\n",
      "Move Number     Starting Position    End Position    Die Used  \n",
      "------------------------------------------------------------\n",
      "0               7                    1               6         \n",
      "1               23                   17              6         \n",
      "2               19                   13              6         \n",
      "3               12                   6               6         \n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Choose an eligible move:  3\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\u001b[1mPlayer 2 Home\u001b[0m\n",
      "\n",
      "Pieces Born Off: 0\n",
      "------------------------------\n",
      "\n",
      "23    -    2\n",
      "22    -    -1\n",
      "21    -    -1\n",
      "20    -    0\n",
      "19    -    1\n",
      "18    -    -5\n",
      "\n",
      "Player 1 Pieces on Bar: 0\n",
      "\n",
      "17    -    0\n",
      "16    -    0\n",
      "15    -    0\n",
      "14    -    0\n",
      "13    -    0\n",
      "12    -    4\n",
      "11    -    -5\n",
      "10    -    -1\n",
      "9    -    0\n",
      "8    -    0\n",
      "7    -    3\n",
      "6    -    1\n",
      "\n",
      "Player 2 Pieces on Bar: -1\n",
      "\n",
      "5    -    -1\n",
      "4    -    0\n",
      "3    -    4\n",
      "2    -    0\n",
      "1    -    0\n",
      "0    -    0\n",
      "\n",
      "------------------------------\n",
      "Pieces Born Off: 0\n",
      "\n",
      "\u001b[1mPlayer 1 Home\u001b[0m\n",
      "\n",
      "\n",
      "Switching Turns...\n",
      "Player 2's Turn\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Press enter to roll die \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "You rolled [1, 6]\n",
      "4\n",
      "\n",
      "\n",
      "\u001b[1mPlayer 2 Home\u001b[0m\n",
      "\n",
      "Pieces Born Off: 0\n",
      "------------------------------\n",
      "\n",
      "23    -    2\n",
      "22    -    -1\n",
      "21    -    -1\n",
      "20    -    0\n",
      "19    -    1\n",
      "18    -    -5\n",
      "\n",
      "Player 1 Pieces on Bar: 0\n",
      "\n",
      "17    -    0\n",
      "16    -    0\n",
      "15    -    0\n",
      "14    -    0\n",
      "13    -    0\n",
      "12    -    4\n",
      "11    -    -5\n",
      "10    -    -1\n",
      "9    -    0\n",
      "8    -    0\n",
      "7    -    3\n",
      "6    -    1\n",
      "\n",
      "Player 2 Pieces on Bar: -1\n",
      "\n",
      "5    -    -1\n",
      "4    -    0\n",
      "3    -    4\n",
      "2    -    0\n",
      "1    -    0\n",
      "0    -    0\n",
      "\n",
      "------------------------------\n",
      "Pieces Born Off: 0\n",
      "\n",
      "\u001b[1mPlayer 1 Home\u001b[0m\n",
      "\n",
      "\n",
      "Must remove pieces from bar first!\n",
      "Move Number     Starting Position    End Position    Die Used  \n",
      "------------------------------------------------------------\n",
      "0               Bar                  0               1         \n",
      "1               Bar                  5               6         \n"
     ]
    }
   ],
   "source": [
    "print(\"Loading Game...\")\n",
    "import numpy as np\n",
    "import time\n",
    "time.sleep(1)\n",
    "\n",
    "class dice:\n",
    "    def roll(self):\n",
    "        return np.random.randint(1, 7), np.random.randint(1, 7)\n",
    "    def rollValues(self):\n",
    "        d1, d2 = self.roll()\n",
    "        if d1 == d2:\n",
    "            return [d1, d1, d1, d1]\n",
    "        else:\n",
    "            return [d1, d2]\n",
    "\n",
    "    def firstTurn(self):\n",
    "        while True:\n",
    "            d1, d2 = np.random.randint(1, 7), np.random.randint(1, 7)\n",
    "            print(f\"Player 1 rolled a {d1}, Player 2 rolled a {d2}\")\n",
    "            time.sleep(1)\n",
    "            if d1 > d2:\n",
    "                print(f\"{d1} is higher than {d2} so Player 1 goes first!\")\n",
    "                time.sleep(1)\n",
    "                print(f\"Starting die are {d1} and {d2}\")\n",
    "                return 1, [d1, d2]\n",
    "            elif d2 > d1:\n",
    "                print(f\"{d2} is higher than {d1} so Player 2 goes first!\")\n",
    "                time.sleep(2)\n",
    "                print(f\"Starting die are {d1} and {d2}\")\n",
    "                return -1, [d1, d2]\n",
    "            print(\"Re-rolling, no dice is higher.\")\n",
    "            time.sleep(1)\n",
    "        \n",
    "class gameBoard:\n",
    "    \n",
    "    def __init__(self):\n",
    "        self.board = np.zeros(24, dtype=int) #shows +x for player 1 tokens and -x for player 2 tokens\n",
    "        self.bar = np.zeros(2, dtype=int) #length two array, shows +x of your tokens on bar and -x of opponent tokens on bar\n",
    "        self.offBoard = np.zeros(2, dtype=int) #ibid\n",
    "        self.initializeBoardPosition()\n",
    "       \n",
    "    def initializeBoardPosition(self):\n",
    "        self.board[0] = -2\n",
    "        self.board[5] = 5\n",
    "        self.board[7] = 3\n",
    "        self.board[11] = -5\n",
    "        self.board[12] = 5\n",
    "        self.board[16] = -3\n",
    "        self.board[18] = -5\n",
    "        self.board[23] = 2\n",
    "\n",
    "    def regions(self):\n",
    "        self.Player1Home = self.board[0:6]\n",
    "        self.middleBoard = self.board[6:18]\n",
    "        self.Player2Home = self.board[18:24]\n",
    "\n",
    "    def possibleMove(self, playerNo, rollValues): \n",
    "        if playerNo == 1:\n",
    "            potentialMovesTurnPlayer1 = []\n",
    "            for i in range(len(self.board)):\n",
    "                if self.board[i] >= -1:\n",
    "                    potentialMovesTurnPlayer1.append(i)\n",
    "                    \n",
    "            positionsWithPresencePlayer1 = []\n",
    "            for i in range(len(self.board)):\n",
    "                if self.board[i] >= 1:\n",
    "                    positionsWithPresencePlayer1.append(i)\n",
    "            \n",
    "            possibleMovesPlayer1 = []\n",
    "            for position in positionsWithPresencePlayer1:\n",
    "                for dieValue in rollValues:\n",
    "                    targetPosition = position - dieValue\n",
    "\n",
    "                    if 0 <= targetPosition < len(self.board):\n",
    "                    \n",
    "                        if targetPosition in potentialMovesTurnPlayer1:\n",
    "                            possibleMovesPlayer1.append((position, targetPosition, dieValue))\n",
    "            return possibleMovesPlayer1\n",
    "                \n",
    "        elif playerNo == -1:\n",
    "            potentialMovesTurnPlayer2 = []\n",
    "            for i in range(len(self.board)):\n",
    "                if self.board[i] <= 1:\n",
    "                    potentialMovesTurnPlayer2.append(i)\n",
    "                \n",
    "            positionsWithPresencePlayer2 = []\n",
    "            for i in range(len(self.board)):\n",
    "                if self.board[i] <= -1:\n",
    "                    positionsWithPresencePlayer2.append(i)\n",
    "\n",
    "            possibleMovesPlayer2 = []\n",
    "            for position in positionsWithPresencePlayer2:\n",
    "                for dieValue in rollValues:\n",
    "                    targetPosition = position + dieValue\n",
    "\n",
    "                    if 0 <= targetPosition < len(self.board):\n",
    "                    \n",
    "                        if targetPosition in potentialMovesTurnPlayer2:\n",
    "                            possibleMovesPlayer2.append((position, targetPosition, dieValue))\n",
    "            return possibleMovesPlayer2\n",
    "                    \n",
    "    def onBar(self, playerNo, rollValues):\n",
    "        barSpot = 0 if playerNo == 1 else 1\n",
    "          \n",
    "        if self.bar[barSpot] == 0:\n",
    "                return []\n",
    "        else:\n",
    "            print(\"Must remove pieces from bar first!\")\n",
    "            possibleMovesBar = []\n",
    "            for dieValue in rollValues:\n",
    "                if playerNo == 1:\n",
    "                    targetPosition = 24 - dieValue\n",
    "                    if self.board[targetPosition] >= -1:\n",
    "                        possibleMovesBar.append((\"Bar\", targetPosition, dieValue))\n",
    "                \n",
    "                elif playerNo == -1:\n",
    "                    targetPosition = dieValue - 1\n",
    "                    if self.board[targetPosition] <= 1:\n",
    "                        possibleMovesBar.append((\"Bar\", targetPosition, dieValue))\n",
    "            return possibleMovesBar\n",
    "            \n",
    "\n",
    "    def pieceCapture(self, playerNo, startingPosition, targetPosition):\n",
    "        if playerNo == 1:\n",
    "            if self.board[targetPosition] == -1:\n",
    "                if startingPosition == \"Bar\":\n",
    "                    self.bar[0] -= 1\n",
    "                else:\n",
    "                    self.board[startingPosition] -= 1\n",
    "                self.board[targetPosition] = 1\n",
    "                self.bar[1] -= 1   \n",
    "\n",
    "        elif playerNo == -1:\n",
    "            if self.board[targetPosition] == 1:\n",
    "                if startingPosition == \"Bar\":\n",
    "                    self.bar[1] += 1\n",
    "                else: \n",
    "                    self.board[startingPosition] += 1\n",
    "                self.board[targetPosition] = -1\n",
    "                self.bar[0] += 1\n",
    "                                     \n",
    "\n",
    "    def move(self, playerNo, startingPosition, targetPosition):\n",
    "        if playerNo == 1:\n",
    "            if startingPosition == \"Bar\":\n",
    "                self.bar[0] -= 1\n",
    "            else:\n",
    "                self.board[startingPosition] -= 1\n",
    "            if targetPosition == \"Bear Off\":\n",
    "                self.offBoard[0] += 1\n",
    "            else:\n",
    "                self.board[targetPosition] += 1\n",
    "\n",
    "        if playerNo == -1:\n",
    "            if startingPosition == \"Bar\":\n",
    "                self.bar[1] += 1\n",
    "            else:\n",
    "                self.board[startingPosition] += 1\n",
    "            if targetPosition == \"Bear Off\":\n",
    "                self.offBoard[1] -= 1\n",
    "            else:\n",
    "                self.board[targetPosition] -= 1\n",
    "\n",
    "    def displayBoard(self):\n",
    "        print()\n",
    "        print()\n",
    "        print(\"\\033[1m\" + \"Player 2 Home\" + \"\\033[0m\")\n",
    "        print()\n",
    "        print(f\"Pieces Born Off: {self.offBoard[1]}\")\n",
    "        print(\"-\"*30)\n",
    "        print()\n",
    "        for i in range(23, 17, -1):\n",
    "            print(f\"{i}    -    {self.board[i]}\")\n",
    "        print()\n",
    "        print(f\"Player 1 Pieces on Bar: {self.bar[0]}\")\n",
    "        print()\n",
    "        for i in range(17, 5, -1):\n",
    "            print(f\"{i}    -    {self.board[i]}\")\n",
    "        print()\n",
    "        print(f\"Player 2 Pieces on Bar: {self.bar[1]}\")\n",
    "        print()\n",
    "        for i in range(5, -1, -1):\n",
    "            print(f\"{i}    -    {self.board[i]}\")\n",
    "        print()\n",
    "        print(f\"-\"*30 )\n",
    "        print(f\"Pieces Born Off: {self.offBoard[0]}\")\n",
    "        print()\n",
    "        print(\"\\033[1m\" + \"Player 1 Home\" + \"\\033[0m\")\n",
    "        print()\n",
    "        print()\n",
    "\n",
    "class players:\n",
    "    def __init__(self, playerNo):\n",
    "        self.playerNo = playerNo\n",
    "                \n",
    "class endOfGame:\n",
    "\n",
    "    def allHome(self, gameboard, playerNo):\n",
    "        gameboard.regions()\n",
    "        if playerNo == 1:\n",
    "            if gameboard.bar[0] == 0 and all(x <= 0 for x in gameboard.middleBoard) and all(x <= 0 for x in gameboard.Player2Home):\n",
    "                return \"Good to Bear Off\"\n",
    "                \n",
    "        elif playerNo == -1:\n",
    "            if gameboard.bar[1] == 0 and all(x >= 0 for x in gameboard.middleBoard) and all(x >= 0 for x in gameboard.Player1Home):\n",
    "                return \"Good to Bear Off\"\n",
    "                \n",
    "    def bearingOff(self, playerNo, gameboard, rollValues):\n",
    "        if self.allHome(gameboard, playerNo) == \"Good to Bear Off\":\n",
    "            possibleBearOffMoves = []\n",
    "        \n",
    "            if playerNo == 1:\n",
    "                for i in range(6):\n",
    "                    if gameboard.board[i] >= 1:\n",
    "                        for dieValue in rollValues:\n",
    "                            distanceNeeded = i + 1\n",
    "                            if dieValue == distanceNeeded:\n",
    "                                possibleBearOffMoves.append((i, \"Bear Off\", dieValue))\n",
    "\n",
    "                furthestIndex = -1\n",
    "                for i in range(5, -1, -1):\n",
    "                    if gameboard.board[i] >= 1:\n",
    "                        furthestIndex = i\n",
    "                        break\n",
    "                        \n",
    "                for dieValue in rollValues:\n",
    "                    distanceNeeded = furthestIndex + 1\n",
    "                    if furthestIndex != -1 and dieValue > distanceNeeded:\n",
    "                        possibleBearOffMoves.append((furthestIndex, \"Bear Off\", dieValue))\n",
    "    \n",
    "                        \n",
    "            if playerNo == -1:\n",
    "                for i in range(18, 24):\n",
    "                    if gameboard.board[i] <= -1:\n",
    "                        for dieValue in rollValues:\n",
    "                            distanceNeeded = 24 - i\n",
    "                            if dieValue == distanceNeeded:\n",
    "                                possibleBearOffMoves.append((i, \"Bear Off\", dieValue))\n",
    "\n",
    "                furthestIndex = -1\n",
    "                for i in range(18, 24):\n",
    "                    if gameboard.board[i] <= -1:\n",
    "                        furthestIndex = i\n",
    "                        break\n",
    "                        \n",
    "                for dieValue in rollValues:\n",
    "                    distanceNeeded = 24 - furthestIndex\n",
    "                    if furthestIndex != -1 and dieValue > distanceNeeded:\n",
    "                        possibleBearOffMoves.append((furthestIndex, \"Bear Off\", dieValue))\n",
    "            return possibleBearOffMoves\n",
    "                \n",
    "    def endGame(self, playerNo, gameboard):\n",
    "        if playerNo == 1:\n",
    "            if gameboard.offBoard[0] == 15:\n",
    "                return \"Player 1 wins!\"\n",
    "        elif playerNo == -1:\n",
    "            if gameboard.offBoard[1] == -15:\n",
    "                return \"Player 2 wins!\"\n",
    "                \n",
    "    def score(self, playerNo, gameboard):\n",
    "        if self.endGame(playerNo, gameboard) == \"Player 1 wins!\":\n",
    "            if gameboard.offBoard[1] != 0:\n",
    "                print(\"Normal Win!\")\n",
    "                return 1\n",
    "            elif gameboard.offBoard[1] == 0 and gameboard.bar[1] == 0 and all(x >= 0 for x in gameboard.board[0:6]):\n",
    "                print(\"Gammon!\")\n",
    "                return 2\n",
    "            else:\n",
    "                print(\"Backgammon!\")\n",
    "                return 3\n",
    "                \n",
    "        if self.endGame(playerNo, gameboard) == \"Player 2 wins!\":\n",
    "            if gameboard.offBoard[0] != 0:\n",
    "                print(\"Normal Win!\")\n",
    "                return 1\n",
    "            elif gameboard.offBoard[0] == 0 and gameboard.bar[0] == 0 and all(x <= 0 for x in gameboard.board[18:24]):\n",
    "                print(\"Gammon!\")\n",
    "                return 2\n",
    "            else:\n",
    "                print(\"Backgammon!\")\n",
    "                return 3\n",
    "\n",
    "def startGame():\n",
    "    print(\"Standard Backgammon Games are often played to 3, 5, 7, 9, 11, or 15 points.\")\n",
    "    while True:\n",
    "        try:\n",
    "            scoreTotal = int(input(\"What score would you like to play to?\"))\n",
    "            if scoreTotal > 0:\n",
    "                break\n",
    "            else:\n",
    "                print(\"Please enter a positive integer.\")\n",
    "        except ValueError:\n",
    "            print(\"Please enter an integer!\")\n",
    "            \n",
    "    gB = gameBoard()\n",
    "    d = dice()\n",
    "    eG = endOfGame()\n",
    "    p1 = players(playerNo=1)\n",
    "    p2 = players(playerNo=-1)\n",
    "    firstPlayerNo, firstRoll = d.firstTurn()\n",
    "    gamePlay(scoreTotal, gB, d, eG, p1, p2, firstPlayerNo, firstRoll)\n",
    "    \n",
    "def gamePlay(scoreTotal, gB, d, eG, p1, p2, firstPlayerNo, firstRoll):\n",
    "    currentPlayer = p1 if firstPlayerNo == 1 else p2\n",
    "    rollValues = firstRoll\n",
    "    turnNumber = 0\n",
    "    scorePlayer1 = 0\n",
    "    scorePlayer2 = 0\n",
    "    while scorePlayer1 < scoreTotal and scorePlayer2 < scoreTotal:\n",
    "        while True:\n",
    "            playerNo = 1 if currentPlayer == p1 else -1\n",
    "            if turnNumber != 0:\n",
    "                input(\"Press enter to roll die\")\n",
    "                rollValues = d.rollValues()\n",
    "                print(f\"You rolled {rollValues}\")\n",
    "            \n",
    "            print(turnNumber)\n",
    "            gB.displayBoard()\n",
    "    \n",
    "            remainingMoves = rollValues.copy()\n",
    "            allMoves = []\n",
    "            while remainingMoves:\n",
    "                barSpot = 0 if playerNo == 1 else 1\n",
    "                if gB.bar[barSpot] != 0:\n",
    "                    allMoves = gB.onBar(playerNo, remainingMoves)\n",
    "         \n",
    "                else:\n",
    "                    bearOffMoves = eG.bearingOff(playerNo, gB, remainingMoves)\n",
    "                    normalMoves = gB.possibleMove(playerNo, remainingMoves)\n",
    "                    allMoves = (bearOffMoves or []) + normalMoves\n",
    "                if not allMoves:\n",
    "                    print(\"No eligible moves, next turn!\")\n",
    "                    break\n",
    "    \n",
    "                allMoves = list(set(allMoves))\n",
    "                \n",
    "                print(f\"{'Move Number':<15} {'Starting Position':<20} {'End Position':<15} {'Die Used':<10}\")\n",
    "                print(\"-\" * 60)\n",
    "                for i, move in enumerate(allMoves):\n",
    "                    print(f\"{str(i):<15} {str(move[0]):<20} {str(move[1]):<15} {str(move[2]):<10}\")\n",
    "                    \n",
    "                while True:\n",
    "                    try:\n",
    "                        moveChosen = int(input(\"Choose an eligible move: \"))\n",
    "                        if 0 <= moveChosen < len(allMoves):\n",
    "                            break\n",
    "                        print(f\"Enter a number between 0 and {len(allMoves) - 1}.\")\n",
    "                    except ValueError:\n",
    "                        print(\"Invalid input. Enter a number.\")\n",
    "    \n",
    "                startingPosition, targetPosition, dieValue = allMoves[moveChosen]\n",
    "    \n",
    "                if targetPosition != \"Bear Off\" and gB.board[int(targetPosition)] == -1 * playerNo:\n",
    "                    gB.pieceCapture(playerNo, startingPosition, targetPosition)\n",
    "                else:\n",
    "                    gB.move(playerNo, startingPosition, targetPosition)\n",
    "                        \n",
    "                remainingMoves.remove(dieValue)\n",
    "                \n",
    "                gB.displayBoard()\n",
    "                \n",
    "            if eG.endGame(playerNo, gB) == \"Player 1 wins!\" or eG.endGame(playerNo, gB) == \"Player 2 wins!\":\n",
    "                score = eG.score(playerNo, gB)\n",
    "                print(f\"Round over! Player {playerNo} score + {score}\")\n",
    "                if eG.endGame(playerNo, gB) == \"Player 1 wins!\":\n",
    "                    scorePlayer1 += score\n",
    "                else:\n",
    "                    scorePlayer2 += score\n",
    "                break\n",
    "            else:\n",
    "                currentPlayer = p1 if currentPlayer == p2 else p2\n",
    "            turnNumber += 1\n",
    "            print(\"Switching Turns...\")\n",
    "            time.sleep(2)\n",
    "            if currentPlayer == p1:\n",
    "                print(\"Player 1's Turn\")\n",
    "            else:\n",
    "                print(\"Player 2's Turn\")\n",
    "    \n",
    "        print(f\"Match Score | Player 1: {scorePlayer1}, Player 2: {scorePlayer2}\")\n",
    "\n",
    "        if scorePlayer1 < scoreTotal and scorePlayer2 < scoreTotal:\n",
    "            print(\"Starting next round...\")\n",
    "            time.sleep(2)\n",
    "            gB = gameBoard()\n",
    "            firstPlayerNo, firstRoll = d.firstTurn()\n",
    "            currentPlayer = p1 if firstPlayerNo == 1 else p2\n",
    "            rollValues = firstRoll\n",
    "            turnNumber = 0\n",
    "\n",
    "    if scorePlayer1 >= scoreTotal:\n",
    "        print(\"Player 1 wins!!!\")\n",
    "    else:\n",
    "        print(\"Player 2 wins!!!\")\n",
    "\n",
    "print(\"Loaded!\")\n",
    "time.sleep(1)\n",
    "\n",
    "### Run game\n",
    "print(\"Starting Match...\")\n",
    "time.sleep(1)\n",
    "print()\n",
    "startGame()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a7b88793-367e-4e9f-b28d-bbcc3c5d5138",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (baseenv)",
   "language": "python",
   "name": "baseenv"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
